name: Deploy VSCode extension

on:
  create:
    tags:
      - v*
  push:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'chore: release') || startsWith(github.ref, 'refs/tags/')"
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn
      - run: yarn deploy -p ${{ secrets.VSCE_TOKEN }}
